#
# Copyright(c) 2021, Developer : Amit Maurya
#

########################
# OptaPlanner properties
########################

# The solver runs for 30 seconds. To run for 5 minutes use "5m" and for 2 hours use "2h".
optaplanner.solver.termination.spent-limit=30s


# To detect common bugs in your code
# optaplanner.solver.environment-mode=FULL_ASSERT

# optaplanner.solver-config-xml=org/.../timeTableSolverConfig.xml

########################
# Spring Boot properties
########################

logging.pattern.console=%d{HH:mm:ss.SSS} %clr(${LOG_LEVEL_PATTERN:%5p}) %blue([%-15.15t]) %m%n
logging.level.org.optaplanner=DEBUG

timeTable.demoData = LARGE

#spring.h2.console.enabled=true
